---
- name: Get secret
  set_fact:
    vault_secret: >-
      {{ lookup('community.hashi_vault.vault_kv2_get', SECRET_PATH, url=VAULT_URL, engine_mount_point="prod/kv/services", token_file=TOKEN_PATH) }}
