---
- name: Copy Caddy Configuration
  ansible.builtin.copy:
    src: "{{ lookup('env', 'TMPDIR') }}configs/Caddyfile"
    dest: /etc/caddy/Caddyfile

- name: Reload Caddy
  ansible.builtin.systemd:
    name: caddy
    state: restarted
    enabled: true